import Footer from "@/components/Footer";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Montserrat } from "next/font/google";
import Loading from "@/components/Loading";

const montserrat = Montserrat({
  subsets: ["latin"], // Adjust as needed
  weight: ["500", "700"], // Select required font weights
  variable: "--font-montserrat", // Define a CSS variable
});

export const metadata = {
  title: "Travel To Edge",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased w-full relative max-w-[1600px] mx-auto flex flex-col`}
      >
        <Loading />
        <Navbar />
        <div className="px-6 md:px-10 xl:px-24">

          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
